 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
namespace LoginC2S
{
	public class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID ReqClientSecurityInfo = (Nettention.Proud.RmiID)20100+1;
			public const Nettention.Proud.RmiID ReqClientSecurityVerify = (Nettention.Proud.RmiID)20100+2;
			public const Nettention.Proud.RmiID ReqAccountAuthLogin = (Nettention.Proud.RmiID)20100+3;
			public const Nettention.Proud.RmiID ReqMoveToLobby = (Nettention.Proud.RmiID)20100+4;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			ReqClientSecurityInfo,
			ReqClientSecurityVerify,
			ReqAccountAuthLogin,
			ReqMoveToLobby,
		};
	}
}
namespace LoginS2C
{
	public class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID AckClientSecurityInfo = (Nettention.Proud.RmiID)20150+1;
			public const Nettention.Proud.RmiID AckClientSecurityVerify = (Nettention.Proud.RmiID)20150+2;
			public const Nettention.Proud.RmiID NotiFirstLogin = (Nettention.Proud.RmiID)20150+3;
			public const Nettention.Proud.RmiID NotiUserLoginChangeData = (Nettention.Proud.RmiID)20150+4;
			public const Nettention.Proud.RmiID AckErrLoginUserBlock = (Nettention.Proud.RmiID)20150+5;
			public const Nettention.Proud.RmiID AckLoginAndUserInfo = (Nettention.Proud.RmiID)20150+6;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			AckClientSecurityInfo,
			AckClientSecurityVerify,
			NotiFirstLogin,
			NotiUserLoginChangeData,
			AckErrLoginUserBlock,
			AckLoginAndUserInfo,
		};
	}
}

				 
