 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
namespace GlobalC2S
{
	public class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID ReqPing = (Nettention.Proud.RmiID)30000+1;
			public const Nettention.Proud.RmiID ReqLogOnCreditKey = (Nettention.Proud.RmiID)30000+2;
			public const Nettention.Proud.RmiID ReqLogOut = (Nettention.Proud.RmiID)30000+3;
			public const Nettention.Proud.RmiID ReqGetTotlaRelocateCntToNotComplete = (Nettention.Proud.RmiID)30000+4;
			public const Nettention.Proud.RmiID ReqRelocateUserInfoSet = (Nettention.Proud.RmiID)30000+5;
			public const Nettention.Proud.RmiID ReqRelocateUserComplate = (Nettention.Proud.RmiID)30000+6;
			public const Nettention.Proud.RmiID ReqRefrashUserInfo = (Nettention.Proud.RmiID)30000+7;
			public const Nettention.Proud.RmiID ReqReConnectUserInfo = (Nettention.Proud.RmiID)30000+8;
			public const Nettention.Proud.RmiID ReqAccountCode = (Nettention.Proud.RmiID)30000+9;
			public const Nettention.Proud.RmiID ReqAccountSetPassword = (Nettention.Proud.RmiID)30000+10;
			public const Nettention.Proud.RmiID ReqAccountCodeReward = (Nettention.Proud.RmiID)30000+11;
			public const Nettention.Proud.RmiID ReqAccountLinkReward = (Nettention.Proud.RmiID)30000+12;
			public const Nettention.Proud.RmiID ReqLinkAccountList = (Nettention.Proud.RmiID)30000+13;
			public const Nettention.Proud.RmiID ReqAddLinkAccountAuth = (Nettention.Proud.RmiID)30000+14;
			public const Nettention.Proud.RmiID ReqGetUserInfoFromAccountLink = (Nettention.Proud.RmiID)30000+15;
			public const Nettention.Proud.RmiID ReqPushNotifiTokenSet = (Nettention.Proud.RmiID)30000+16;
			public const Nettention.Proud.RmiID ReqReflashLoginBonus = (Nettention.Proud.RmiID)30000+17;
			public const Nettention.Proud.RmiID ReqRewardTakeAchieve = (Nettention.Proud.RmiID)30000+18;
			public const Nettention.Proud.RmiID ReqRewardTakeAchieveEvent = (Nettention.Proud.RmiID)30000+19;
			public const Nettention.Proud.RmiID ReqRewardDailyMission = (Nettention.Proud.RmiID)30000+20;
			public const Nettention.Proud.RmiID ReqRewardWeekMission = (Nettention.Proud.RmiID)30000+21;
			public const Nettention.Proud.RmiID ReqRewardInfluMission = (Nettention.Proud.RmiID)30000+22;
			public const Nettention.Proud.RmiID ReqUpdateGllaMission = (Nettention.Proud.RmiID)30000+23;
			public const Nettention.Proud.RmiID ReqRewardGllaMission = (Nettention.Proud.RmiID)30000+24;
			public const Nettention.Proud.RmiID ReqRewardPassMission = (Nettention.Proud.RmiID)30000+25;
			public const Nettention.Proud.RmiID ReqRewardPass = (Nettention.Proud.RmiID)30000+26;
			public const Nettention.Proud.RmiID ReqEventRewardReset = (Nettention.Proud.RmiID)30000+27;
			public const Nettention.Proud.RmiID ReqEventRewardTake = (Nettention.Proud.RmiID)30000+28;
			public const Nettention.Proud.RmiID ReqEventLgnRewardTake = (Nettention.Proud.RmiID)30000+29;
			public const Nettention.Proud.RmiID ReqSetTutorialVal = (Nettention.Proud.RmiID)30000+30;
			public const Nettention.Proud.RmiID ReqSetTutorialFlag = (Nettention.Proud.RmiID)30000+31;
			public const Nettention.Proud.RmiID ReqAddCharacter = (Nettention.Proud.RmiID)30000+32;
			public const Nettention.Proud.RmiID ReqChangePreferenceNum = (Nettention.Proud.RmiID)30000+33;
			public const Nettention.Proud.RmiID ReqChangeMainChar = (Nettention.Proud.RmiID)30000+34;
			public const Nettention.Proud.RmiID ReqGradeUpChar = (Nettention.Proud.RmiID)30000+35;
			public const Nettention.Proud.RmiID ReqSetMainCostumeChar = (Nettention.Proud.RmiID)30000+36;
			public const Nettention.Proud.RmiID ReqRandomCostumeDyeing = (Nettention.Proud.RmiID)30000+37;
			public const Nettention.Proud.RmiID ReqSetCostumeDyeing = (Nettention.Proud.RmiID)30000+38;
			public const Nettention.Proud.RmiID ReqCostumeDyeingLock = (Nettention.Proud.RmiID)30000+39;
			public const Nettention.Proud.RmiID ReqUserCostumeColor = (Nettention.Proud.RmiID)30000+40;
			public const Nettention.Proud.RmiID ReqEquipWeaponChar = (Nettention.Proud.RmiID)30000+41;
			public const Nettention.Proud.RmiID ReqApplySkillInChar = (Nettention.Proud.RmiID)30000+42;
			public const Nettention.Proud.RmiID ReqLvUpSkill = (Nettention.Proud.RmiID)30000+43;
			public const Nettention.Proud.RmiID ReqLvUpUserSkill = (Nettention.Proud.RmiID)30000+44;
			public const Nettention.Proud.RmiID ReqResetUserSkill = (Nettention.Proud.RmiID)30000+45;
			public const Nettention.Proud.RmiID ReqGivePresentChar = (Nettention.Proud.RmiID)30000+46;
			public const Nettention.Proud.RmiID ReqResetSecretCntChar = (Nettention.Proud.RmiID)30000+47;
			public const Nettention.Proud.RmiID ReqRaidHPRestore = (Nettention.Proud.RmiID)30000+48;
			public const Nettention.Proud.RmiID ReqStageStart = (Nettention.Proud.RmiID)30000+49;
			public const Nettention.Proud.RmiID ReqStageEnd = (Nettention.Proud.RmiID)30000+50;
			public const Nettention.Proud.RmiID ReqStageEndFail = (Nettention.Proud.RmiID)30000+51;
			public const Nettention.Proud.RmiID ReqStageContinue = (Nettention.Proud.RmiID)30000+52;
			public const Nettention.Proud.RmiID ReqRaidStageDrop = (Nettention.Proud.RmiID)30000+53;
			public const Nettention.Proud.RmiID ReqBookNewConfirm = (Nettention.Proud.RmiID)30000+54;
			public const Nettention.Proud.RmiID ReqTimeAtkRankingList = (Nettention.Proud.RmiID)30000+55;
			public const Nettention.Proud.RmiID ReqTimeAtkRankerDetail = (Nettention.Proud.RmiID)30000+56;
			public const Nettention.Proud.RmiID ReqInitRaidSeasonData = (Nettention.Proud.RmiID)30000+57;
			public const Nettention.Proud.RmiID ReqRaidRankingList = (Nettention.Proud.RmiID)30000+58;
			public const Nettention.Proud.RmiID ReqRaidRankerDetail = (Nettention.Proud.RmiID)30000+59;
			public const Nettention.Proud.RmiID ReqRaidFirstRankingList = (Nettention.Proud.RmiID)30000+60;
			public const Nettention.Proud.RmiID ReqRaidFirstRankerDetail = (Nettention.Proud.RmiID)30000+61;
			public const Nettention.Proud.RmiID ReqSetRaidTeam = (Nettention.Proud.RmiID)30000+62;
			public const Nettention.Proud.RmiID ReqArenaSeasonPlay = (Nettention.Proud.RmiID)30000+63;
			public const Nettention.Proud.RmiID ReqSetArenaTeam = (Nettention.Proud.RmiID)30000+64;
			public const Nettention.Proud.RmiID ReqArenaGameStart = (Nettention.Proud.RmiID)30000+65;
			public const Nettention.Proud.RmiID ReqArenaGameEnd = (Nettention.Proud.RmiID)30000+66;
			public const Nettention.Proud.RmiID ReqArenaEnemySearch = (Nettention.Proud.RmiID)30000+67;
			public const Nettention.Proud.RmiID ReqArenaRankingList = (Nettention.Proud.RmiID)30000+68;
			public const Nettention.Proud.RmiID ReqArenaRankerDetail = (Nettention.Proud.RmiID)30000+69;
			public const Nettention.Proud.RmiID ReqSetArenaTowerTeam = (Nettention.Proud.RmiID)30000+70;
			public const Nettention.Proud.RmiID ReqArenaTowerGameStart = (Nettention.Proud.RmiID)30000+71;
			public const Nettention.Proud.RmiID ReqArenaTowerGameEnd = (Nettention.Proud.RmiID)30000+72;
			public const Nettention.Proud.RmiID ReqUnexpectedPackageDailyReward = (Nettention.Proud.RmiID)30000+73;
			public const Nettention.Proud.RmiID ReqCharLvUnexpectedPackageHardOpen = (Nettention.Proud.RmiID)30000+74;
			public const Nettention.Proud.RmiID ReqAccountDelete = (Nettention.Proud.RmiID)30000+75;
			public const Nettention.Proud.RmiID ReqGetUserPresetList = (Nettention.Proud.RmiID)30000+76;
			public const Nettention.Proud.RmiID ReqAddOrUpdateUserPreset = (Nettention.Proud.RmiID)30000+77;
			public const Nettention.Proud.RmiID ReqUserPresetLoad = (Nettention.Proud.RmiID)30000+78;
			public const Nettention.Proud.RmiID ReqUserPresetChangeName = (Nettention.Proud.RmiID)30000+79;
			public const Nettention.Proud.RmiID ReqCircleOpen = (Nettention.Proud.RmiID)30000+80;
			public const Nettention.Proud.RmiID ReqSuggestCircleList = (Nettention.Proud.RmiID)30000+81;
			public const Nettention.Proud.RmiID ReqCircleJoin = (Nettention.Proud.RmiID)30000+82;
			public const Nettention.Proud.RmiID ReqCircleJoinCancel = (Nettention.Proud.RmiID)30000+83;
			public const Nettention.Proud.RmiID ReqCircleLobbyInfo = (Nettention.Proud.RmiID)30000+84;
			public const Nettention.Proud.RmiID ReqCircleWithdrawal = (Nettention.Proud.RmiID)30000+85;
			public const Nettention.Proud.RmiID ReqCircleDisperse = (Nettention.Proud.RmiID)30000+86;
			public const Nettention.Proud.RmiID ReqGetCircleUserList = (Nettention.Proud.RmiID)30000+87;
			public const Nettention.Proud.RmiID ReqCircleChangeStateJoinWaitUser = (Nettention.Proud.RmiID)30000+88;
			public const Nettention.Proud.RmiID ReqCircleUserKick = (Nettention.Proud.RmiID)30000+89;
			public const Nettention.Proud.RmiID ReqCircleChangeAuthLevel = (Nettention.Proud.RmiID)30000+90;
			public const Nettention.Proud.RmiID ReqCircleChangeMark = (Nettention.Proud.RmiID)30000+91;
			public const Nettention.Proud.RmiID ReqCircleChangeName = (Nettention.Proud.RmiID)30000+92;
			public const Nettention.Proud.RmiID ReqCircleChangeComment = (Nettention.Proud.RmiID)30000+93;
			public const Nettention.Proud.RmiID ReqCircleChangeMainLanguage = (Nettention.Proud.RmiID)30000+94;
			public const Nettention.Proud.RmiID ReqCircleChangeSuggestAnotherLangOpt = (Nettention.Proud.RmiID)30000+95;
			public const Nettention.Proud.RmiID ReqCircleAttendance = (Nettention.Proud.RmiID)30000+96;
			public const Nettention.Proud.RmiID ReqCircleBuyMarkItem = (Nettention.Proud.RmiID)30000+97;
			public const Nettention.Proud.RmiID ReqCircleChatSend = (Nettention.Proud.RmiID)30000+98;
			public const Nettention.Proud.RmiID ReqCircleGetMarkList = (Nettention.Proud.RmiID)30000+99;
			public const Nettention.Proud.RmiID ReqCircleSearch = (Nettention.Proud.RmiID)30000+100;
			public const Nettention.Proud.RmiID ReqCircleChatList = (Nettention.Proud.RmiID)30000+101;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			ReqPing,
			ReqLogOnCreditKey,
			ReqLogOut,
			ReqGetTotlaRelocateCntToNotComplete,
			ReqRelocateUserInfoSet,
			ReqRelocateUserComplate,
			ReqRefrashUserInfo,
			ReqReConnectUserInfo,
			ReqAccountCode,
			ReqAccountSetPassword,
			ReqAccountCodeReward,
			ReqAccountLinkReward,
			ReqLinkAccountList,
			ReqAddLinkAccountAuth,
			ReqGetUserInfoFromAccountLink,
			ReqPushNotifiTokenSet,
			ReqReflashLoginBonus,
			ReqRewardTakeAchieve,
			ReqRewardTakeAchieveEvent,
			ReqRewardDailyMission,
			ReqRewardWeekMission,
			ReqRewardInfluMission,
			ReqUpdateGllaMission,
			ReqRewardGllaMission,
			ReqRewardPassMission,
			ReqRewardPass,
			ReqEventRewardReset,
			ReqEventRewardTake,
			ReqEventLgnRewardTake,
			ReqSetTutorialVal,
			ReqSetTutorialFlag,
			ReqAddCharacter,
			ReqChangePreferenceNum,
			ReqChangeMainChar,
			ReqGradeUpChar,
			ReqSetMainCostumeChar,
			ReqRandomCostumeDyeing,
			ReqSetCostumeDyeing,
			ReqCostumeDyeingLock,
			ReqUserCostumeColor,
			ReqEquipWeaponChar,
			ReqApplySkillInChar,
			ReqLvUpSkill,
			ReqLvUpUserSkill,
			ReqResetUserSkill,
			ReqGivePresentChar,
			ReqResetSecretCntChar,
			ReqRaidHPRestore,
			ReqStageStart,
			ReqStageEnd,
			ReqStageEndFail,
			ReqStageContinue,
			ReqRaidStageDrop,
			ReqBookNewConfirm,
			ReqTimeAtkRankingList,
			ReqTimeAtkRankerDetail,
			ReqInitRaidSeasonData,
			ReqRaidRankingList,
			ReqRaidRankerDetail,
			ReqRaidFirstRankingList,
			ReqRaidFirstRankerDetail,
			ReqSetRaidTeam,
			ReqArenaSeasonPlay,
			ReqSetArenaTeam,
			ReqArenaGameStart,
			ReqArenaGameEnd,
			ReqArenaEnemySearch,
			ReqArenaRankingList,
			ReqArenaRankerDetail,
			ReqSetArenaTowerTeam,
			ReqArenaTowerGameStart,
			ReqArenaTowerGameEnd,
			ReqUnexpectedPackageDailyReward,
			ReqCharLvUnexpectedPackageHardOpen,
			ReqAccountDelete,
			ReqGetUserPresetList,
			ReqAddOrUpdateUserPreset,
			ReqUserPresetLoad,
			ReqUserPresetChangeName,
			ReqCircleOpen,
			ReqSuggestCircleList,
			ReqCircleJoin,
			ReqCircleJoinCancel,
			ReqCircleLobbyInfo,
			ReqCircleWithdrawal,
			ReqCircleDisperse,
			ReqGetCircleUserList,
			ReqCircleChangeStateJoinWaitUser,
			ReqCircleUserKick,
			ReqCircleChangeAuthLevel,
			ReqCircleChangeMark,
			ReqCircleChangeName,
			ReqCircleChangeComment,
			ReqCircleChangeMainLanguage,
			ReqCircleChangeSuggestAnotherLangOpt,
			ReqCircleAttendance,
			ReqCircleBuyMarkItem,
			ReqCircleChatSend,
			ReqCircleGetMarkList,
			ReqCircleSearch,
			ReqCircleChatList,
		};
	}
}
namespace GlobalS2C
{
	public class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID NotiSvrReloadTableInfo = (Nettention.Proud.RmiID)30200+1;
			public const Nettention.Proud.RmiID NotiCloseServTime = (Nettention.Proud.RmiID)30200+2;
			public const Nettention.Proud.RmiID NotiCommonErr = (Nettention.Proud.RmiID)30200+3;
			public const Nettention.Proud.RmiID NotiEmbargoWordErr = (Nettention.Proud.RmiID)30200+4;
			public const Nettention.Proud.RmiID NotiCheckVersionErr = (Nettention.Proud.RmiID)30200+5;
			public const Nettention.Proud.RmiID NotiMoveUserInSvrToSvr = (Nettention.Proud.RmiID)30200+6;
			public const Nettention.Proud.RmiID NotiUpdateTicket = (Nettention.Proud.RmiID)30200+7;
			public const Nettention.Proud.RmiID NotiUserMarkTake = (Nettention.Proud.RmiID)30200+8;
			public const Nettention.Proud.RmiID NotiAddMail = (Nettention.Proud.RmiID)30200+9;
			public const Nettention.Proud.RmiID NotiUpdateAchieve = (Nettention.Proud.RmiID)30200+10;
			public const Nettention.Proud.RmiID NotiUpdateAchieveEvent = (Nettention.Proud.RmiID)30200+11;
			public const Nettention.Proud.RmiID NotiSetSvrRotationGacha = (Nettention.Proud.RmiID)30200+12;
			public const Nettention.Proud.RmiID NotiSetSvrSecretQuestOpt = (Nettention.Proud.RmiID)30200+13;
			public const Nettention.Proud.RmiID NotiUpdateDailyMission = (Nettention.Proud.RmiID)30200+14;
			public const Nettention.Proud.RmiID NotiResetWeekMission = (Nettention.Proud.RmiID)30200+15;
			public const Nettention.Proud.RmiID NotiUpdateWeekMission = (Nettention.Proud.RmiID)30200+16;
			public const Nettention.Proud.RmiID NotiUpdateInfluMission = (Nettention.Proud.RmiID)30200+17;
			public const Nettention.Proud.RmiID NotiUserInfluMissionChange = (Nettention.Proud.RmiID)30200+18;
			public const Nettention.Proud.RmiID NotiUpdateGllaMission = (Nettention.Proud.RmiID)30200+19;
			public const Nettention.Proud.RmiID NotiUpdatePassMission = (Nettention.Proud.RmiID)30200+20;
			public const Nettention.Proud.RmiID NotiUserPassChange = (Nettention.Proud.RmiID)30200+21;
			public const Nettention.Proud.RmiID NotiUserEventChange = (Nettention.Proud.RmiID)30200+22;
			public const Nettention.Proud.RmiID NotiUpdateArenaTime = (Nettention.Proud.RmiID)30200+23;
			public const Nettention.Proud.RmiID NotiUpdateRaidTime = (Nettention.Proud.RmiID)30200+24;
			public const Nettention.Proud.RmiID NotiUpdateRaidInitStart = (Nettention.Proud.RmiID)30200+25;
			public const Nettention.Proud.RmiID NotiCommunityUserArenaOn = (Nettention.Proud.RmiID)30200+26;
			public const Nettention.Proud.RmiID NotiCommunityUserCallCnt = (Nettention.Proud.RmiID)30200+27;
			public const Nettention.Proud.RmiID NotiCommunitySetArenaTowerID = (Nettention.Proud.RmiID)30200+28;
			public const Nettention.Proud.RmiID NotiFriendFromAdd = (Nettention.Proud.RmiID)30200+29;
			public const Nettention.Proud.RmiID NotiFriendFromDel = (Nettention.Proud.RmiID)30200+30;
			public const Nettention.Proud.RmiID NotiFriendAnswer = (Nettention.Proud.RmiID)30200+31;
			public const Nettention.Proud.RmiID NotiFriendKick = (Nettention.Proud.RmiID)30200+32;
			public const Nettention.Proud.RmiID NotiFriendFlagUpdate = (Nettention.Proud.RmiID)30200+33;
			public const Nettention.Proud.RmiID AckPing = (Nettention.Proud.RmiID)30200+34;
			public const Nettention.Proud.RmiID AckLogOnCreditKey = (Nettention.Proud.RmiID)30200+35;
			public const Nettention.Proud.RmiID AckLogOut = (Nettention.Proud.RmiID)30200+36;
			public const Nettention.Proud.RmiID AckGetTotlaRelocateCntToNotComplete = (Nettention.Proud.RmiID)30200+37;
			public const Nettention.Proud.RmiID AckRelocateUserInfoSet = (Nettention.Proud.RmiID)30200+38;
			public const Nettention.Proud.RmiID AckRelocateUserComplate = (Nettention.Proud.RmiID)30200+39;
			public const Nettention.Proud.RmiID AckRefrashUserInfo = (Nettention.Proud.RmiID)30200+40;
			public const Nettention.Proud.RmiID AckReConnectUserInfo = (Nettention.Proud.RmiID)30200+41;
			public const Nettention.Proud.RmiID AckAccountCode = (Nettention.Proud.RmiID)30200+42;
			public const Nettention.Proud.RmiID AckAccountSetPassword = (Nettention.Proud.RmiID)30200+43;
			public const Nettention.Proud.RmiID AckAccountCodeReward = (Nettention.Proud.RmiID)30200+44;
			public const Nettention.Proud.RmiID AckAccountLinkReward = (Nettention.Proud.RmiID)30200+45;
			public const Nettention.Proud.RmiID AckLinkAccountList = (Nettention.Proud.RmiID)30200+46;
			public const Nettention.Proud.RmiID AckAddLinkAccountAuth = (Nettention.Proud.RmiID)30200+47;
			public const Nettention.Proud.RmiID AckGetUserInfoFromAccountLink = (Nettention.Proud.RmiID)30200+48;
			public const Nettention.Proud.RmiID AckPushNotifiTokenSet = (Nettention.Proud.RmiID)30200+49;
			public const Nettention.Proud.RmiID AckReflashLoginBonus = (Nettention.Proud.RmiID)30200+50;
			public const Nettention.Proud.RmiID AckRewardTakeAchieve = (Nettention.Proud.RmiID)30200+51;
			public const Nettention.Proud.RmiID AckRewardTakeAchieveEvent = (Nettention.Proud.RmiID)30200+52;
			public const Nettention.Proud.RmiID AckRewardDailyMission = (Nettention.Proud.RmiID)30200+53;
			public const Nettention.Proud.RmiID AckRewardWeekMission = (Nettention.Proud.RmiID)30200+54;
			public const Nettention.Proud.RmiID AckRewardInfluMission = (Nettention.Proud.RmiID)30200+55;
			public const Nettention.Proud.RmiID AckUpdateGllaMission = (Nettention.Proud.RmiID)30200+56;
			public const Nettention.Proud.RmiID AckRewardGllaMission = (Nettention.Proud.RmiID)30200+57;
			public const Nettention.Proud.RmiID AckRewardPassMission = (Nettention.Proud.RmiID)30200+58;
			public const Nettention.Proud.RmiID AckRewardPass = (Nettention.Proud.RmiID)30200+59;
			public const Nettention.Proud.RmiID AckEventRewardReset = (Nettention.Proud.RmiID)30200+60;
			public const Nettention.Proud.RmiID AckEventRewardTake = (Nettention.Proud.RmiID)30200+61;
			public const Nettention.Proud.RmiID AckEventLgnRewardTake = (Nettention.Proud.RmiID)30200+62;
			public const Nettention.Proud.RmiID AckSetTutorialVal = (Nettention.Proud.RmiID)30200+63;
			public const Nettention.Proud.RmiID AckSetTutorialFlag = (Nettention.Proud.RmiID)30200+64;
			public const Nettention.Proud.RmiID AckAddCharacter = (Nettention.Proud.RmiID)30200+65;
			public const Nettention.Proud.RmiID AckChangePreferenceNum = (Nettention.Proud.RmiID)30200+66;
			public const Nettention.Proud.RmiID AckChangeMainChar = (Nettention.Proud.RmiID)30200+67;
			public const Nettention.Proud.RmiID AckGradeUpChar = (Nettention.Proud.RmiID)30200+68;
			public const Nettention.Proud.RmiID AckSetGradeLvChar = (Nettention.Proud.RmiID)30200+69;
			public const Nettention.Proud.RmiID AckSetMainCostumeChar = (Nettention.Proud.RmiID)30200+70;
			public const Nettention.Proud.RmiID AckRandomCostumeDyeing = (Nettention.Proud.RmiID)30200+71;
			public const Nettention.Proud.RmiID AckSetCostumeDyeing = (Nettention.Proud.RmiID)30200+72;
			public const Nettention.Proud.RmiID AckCostumeDyeingLock = (Nettention.Proud.RmiID)30200+73;
			public const Nettention.Proud.RmiID AckUserCostumeColor = (Nettention.Proud.RmiID)30200+74;
			public const Nettention.Proud.RmiID AckEquipWeaponChar = (Nettention.Proud.RmiID)30200+75;
			public const Nettention.Proud.RmiID AckApplySkillInChar = (Nettention.Proud.RmiID)30200+76;
			public const Nettention.Proud.RmiID AckLvUpSkill = (Nettention.Proud.RmiID)30200+77;
			public const Nettention.Proud.RmiID AckLvUpUserSkill = (Nettention.Proud.RmiID)30200+78;
			public const Nettention.Proud.RmiID AckResetUserSkill = (Nettention.Proud.RmiID)30200+79;
			public const Nettention.Proud.RmiID AckGivePresentChar = (Nettention.Proud.RmiID)30200+80;
			public const Nettention.Proud.RmiID AckResetSecretCntChar = (Nettention.Proud.RmiID)30200+81;
			public const Nettention.Proud.RmiID AckRaidHPRestore = (Nettention.Proud.RmiID)30200+82;
			public const Nettention.Proud.RmiID AckStageStart = (Nettention.Proud.RmiID)30200+83;
			public const Nettention.Proud.RmiID AckStageEnd = (Nettention.Proud.RmiID)30200+84;
			public const Nettention.Proud.RmiID AckStageEndFail = (Nettention.Proud.RmiID)30200+85;
			public const Nettention.Proud.RmiID AckStageContinue = (Nettention.Proud.RmiID)30200+86;
			public const Nettention.Proud.RmiID AckRaidStageDrop = (Nettention.Proud.RmiID)30200+87;
			public const Nettention.Proud.RmiID AckBookNewConfirm = (Nettention.Proud.RmiID)30200+88;
			public const Nettention.Proud.RmiID AckTimeAtkRankingList = (Nettention.Proud.RmiID)30200+89;
			public const Nettention.Proud.RmiID AckTimeAtkRankerDetail = (Nettention.Proud.RmiID)30200+90;
			public const Nettention.Proud.RmiID AckInitRaidSeasonData = (Nettention.Proud.RmiID)30200+91;
			public const Nettention.Proud.RmiID AckRaidRankingList = (Nettention.Proud.RmiID)30200+92;
			public const Nettention.Proud.RmiID AckRaidRankerDetail = (Nettention.Proud.RmiID)30200+93;
			public const Nettention.Proud.RmiID AckRaidFirstRankingList = (Nettention.Proud.RmiID)30200+94;
			public const Nettention.Proud.RmiID AckRaidFirstRankerDetail = (Nettention.Proud.RmiID)30200+95;
			public const Nettention.Proud.RmiID AckSetRaidTeam = (Nettention.Proud.RmiID)30200+96;
			public const Nettention.Proud.RmiID AckArenaSeasonPlay = (Nettention.Proud.RmiID)30200+97;
			public const Nettention.Proud.RmiID AckSetArenaTeam = (Nettention.Proud.RmiID)30200+98;
			public const Nettention.Proud.RmiID AckArenaGameStart = (Nettention.Proud.RmiID)30200+99;
			public const Nettention.Proud.RmiID AckArenaGameEnd = (Nettention.Proud.RmiID)30200+100;
			public const Nettention.Proud.RmiID AckArenaEnemySearch = (Nettention.Proud.RmiID)30200+101;
			public const Nettention.Proud.RmiID AckArenaRankingList = (Nettention.Proud.RmiID)30200+102;
			public const Nettention.Proud.RmiID AckArenaRankerDetail = (Nettention.Proud.RmiID)30200+103;
			public const Nettention.Proud.RmiID AckSetArenaTowerTeam = (Nettention.Proud.RmiID)30200+104;
			public const Nettention.Proud.RmiID AckArenaTowerGameStart = (Nettention.Proud.RmiID)30200+105;
			public const Nettention.Proud.RmiID AckArenaTowerGameEnd = (Nettention.Proud.RmiID)30200+106;
			public const Nettention.Proud.RmiID AckUnexpectedPackageDailyReward = (Nettention.Proud.RmiID)30200+107;
			public const Nettention.Proud.RmiID AckCharLvUnexpectedPackageHardOpen = (Nettention.Proud.RmiID)30200+108;
			public const Nettention.Proud.RmiID AckAccountDelete = (Nettention.Proud.RmiID)30200+109;
			public const Nettention.Proud.RmiID AckGetUserPresetList = (Nettention.Proud.RmiID)30200+110;
			public const Nettention.Proud.RmiID AckAddOrUpdateUserPreset = (Nettention.Proud.RmiID)30200+111;
			public const Nettention.Proud.RmiID AckUserPresetLoad = (Nettention.Proud.RmiID)30200+112;
			public const Nettention.Proud.RmiID AckUserPresetChangeName = (Nettention.Proud.RmiID)30200+113;
			public const Nettention.Proud.RmiID AckCircleOpen = (Nettention.Proud.RmiID)30200+114;
			public const Nettention.Proud.RmiID AckSuggestCircleList = (Nettention.Proud.RmiID)30200+115;
			public const Nettention.Proud.RmiID AckCircleJoin = (Nettention.Proud.RmiID)30200+116;
			public const Nettention.Proud.RmiID AckCircleJoinCancel = (Nettention.Proud.RmiID)30200+117;
			public const Nettention.Proud.RmiID AckCircleLobbyInfo = (Nettention.Proud.RmiID)30200+118;
			public const Nettention.Proud.RmiID AckCircleWithdrawal = (Nettention.Proud.RmiID)30200+119;
			public const Nettention.Proud.RmiID AckCircleDisperse = (Nettention.Proud.RmiID)30200+120;
			public const Nettention.Proud.RmiID AckGetCircleUserList = (Nettention.Proud.RmiID)30200+121;
			public const Nettention.Proud.RmiID AckCircleChangeStateJoinWaitUser = (Nettention.Proud.RmiID)30200+122;
			public const Nettention.Proud.RmiID NotiCircleAcceptJoin = (Nettention.Proud.RmiID)30200+123;
			public const Nettention.Proud.RmiID AckCircleUserKick = (Nettention.Proud.RmiID)30200+124;
			public const Nettention.Proud.RmiID NotiCircleUserKick = (Nettention.Proud.RmiID)30200+125;
			public const Nettention.Proud.RmiID AckCircleChangeAuthLevel = (Nettention.Proud.RmiID)30200+126;
			public const Nettention.Proud.RmiID NotiCircleUserChangeAuth = (Nettention.Proud.RmiID)30200+127;
			public const Nettention.Proud.RmiID AckCircleChangeMark = (Nettention.Proud.RmiID)30200+128;
			public const Nettention.Proud.RmiID AckCircleChangeName = (Nettention.Proud.RmiID)30200+129;
			public const Nettention.Proud.RmiID AckCircleChangeComment = (Nettention.Proud.RmiID)30200+130;
			public const Nettention.Proud.RmiID AckCircleChangeMainLanguage = (Nettention.Proud.RmiID)30200+131;
			public const Nettention.Proud.RmiID AckCircleChangeSuggestAnotherLangOpt = (Nettention.Proud.RmiID)30200+132;
			public const Nettention.Proud.RmiID AckCircleAttendance = (Nettention.Proud.RmiID)30200+133;
			public const Nettention.Proud.RmiID AckCircleBuyMarkItem = (Nettention.Proud.RmiID)30200+134;
			public const Nettention.Proud.RmiID NotiCircleChat = (Nettention.Proud.RmiID)30200+135;
			public const Nettention.Proud.RmiID AckCircleGetMarkList = (Nettention.Proud.RmiID)30200+136;
			public const Nettention.Proud.RmiID AckCircleSearch = (Nettention.Proud.RmiID)30200+137;
			public const Nettention.Proud.RmiID AckCircleChatList = (Nettention.Proud.RmiID)30200+138;
			public const Nettention.Proud.RmiID NotiCircleChatNotimessage = (Nettention.Proud.RmiID)30200+139;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			NotiSvrReloadTableInfo,
			NotiCloseServTime,
			NotiCommonErr,
			NotiEmbargoWordErr,
			NotiCheckVersionErr,
			NotiMoveUserInSvrToSvr,
			NotiUpdateTicket,
			NotiUserMarkTake,
			NotiAddMail,
			NotiUpdateAchieve,
			NotiUpdateAchieveEvent,
			NotiSetSvrRotationGacha,
			NotiSetSvrSecretQuestOpt,
			NotiUpdateDailyMission,
			NotiResetWeekMission,
			NotiUpdateWeekMission,
			NotiUpdateInfluMission,
			NotiUserInfluMissionChange,
			NotiUpdateGllaMission,
			NotiUpdatePassMission,
			NotiUserPassChange,
			NotiUserEventChange,
			NotiUpdateArenaTime,
			NotiUpdateRaidTime,
			NotiUpdateRaidInitStart,
			NotiCommunityUserArenaOn,
			NotiCommunityUserCallCnt,
			NotiCommunitySetArenaTowerID,
			NotiFriendFromAdd,
			NotiFriendFromDel,
			NotiFriendAnswer,
			NotiFriendKick,
			NotiFriendFlagUpdate,
			AckPing,
			AckLogOnCreditKey,
			AckLogOut,
			AckGetTotlaRelocateCntToNotComplete,
			AckRelocateUserInfoSet,
			AckRelocateUserComplate,
			AckRefrashUserInfo,
			AckReConnectUserInfo,
			AckAccountCode,
			AckAccountSetPassword,
			AckAccountCodeReward,
			AckAccountLinkReward,
			AckLinkAccountList,
			AckAddLinkAccountAuth,
			AckGetUserInfoFromAccountLink,
			AckPushNotifiTokenSet,
			AckReflashLoginBonus,
			AckRewardTakeAchieve,
			AckRewardTakeAchieveEvent,
			AckRewardDailyMission,
			AckRewardWeekMission,
			AckRewardInfluMission,
			AckUpdateGllaMission,
			AckRewardGllaMission,
			AckRewardPassMission,
			AckRewardPass,
			AckEventRewardReset,
			AckEventRewardTake,
			AckEventLgnRewardTake,
			AckSetTutorialVal,
			AckSetTutorialFlag,
			AckAddCharacter,
			AckChangePreferenceNum,
			AckChangeMainChar,
			AckGradeUpChar,
			AckSetGradeLvChar,
			AckSetMainCostumeChar,
			AckRandomCostumeDyeing,
			AckSetCostumeDyeing,
			AckCostumeDyeingLock,
			AckUserCostumeColor,
			AckEquipWeaponChar,
			AckApplySkillInChar,
			AckLvUpSkill,
			AckLvUpUserSkill,
			AckResetUserSkill,
			AckGivePresentChar,
			AckResetSecretCntChar,
			AckRaidHPRestore,
			AckStageStart,
			AckStageEnd,
			AckStageEndFail,
			AckStageContinue,
			AckRaidStageDrop,
			AckBookNewConfirm,
			AckTimeAtkRankingList,
			AckTimeAtkRankerDetail,
			AckInitRaidSeasonData,
			AckRaidRankingList,
			AckRaidRankerDetail,
			AckRaidFirstRankingList,
			AckRaidFirstRankerDetail,
			AckSetRaidTeam,
			AckArenaSeasonPlay,
			AckSetArenaTeam,
			AckArenaGameStart,
			AckArenaGameEnd,
			AckArenaEnemySearch,
			AckArenaRankingList,
			AckArenaRankerDetail,
			AckSetArenaTowerTeam,
			AckArenaTowerGameStart,
			AckArenaTowerGameEnd,
			AckUnexpectedPackageDailyReward,
			AckCharLvUnexpectedPackageHardOpen,
			AckAccountDelete,
			AckGetUserPresetList,
			AckAddOrUpdateUserPreset,
			AckUserPresetLoad,
			AckUserPresetChangeName,
			AckCircleOpen,
			AckSuggestCircleList,
			AckCircleJoin,
			AckCircleJoinCancel,
			AckCircleLobbyInfo,
			AckCircleWithdrawal,
			AckCircleDisperse,
			AckGetCircleUserList,
			AckCircleChangeStateJoinWaitUser,
			NotiCircleAcceptJoin,
			AckCircleUserKick,
			NotiCircleUserKick,
			AckCircleChangeAuthLevel,
			NotiCircleUserChangeAuth,
			AckCircleChangeMark,
			AckCircleChangeName,
			AckCircleChangeComment,
			AckCircleChangeMainLanguage,
			AckCircleChangeSuggestAnotherLangOpt,
			AckCircleAttendance,
			AckCircleBuyMarkItem,
			NotiCircleChat,
			AckCircleGetMarkList,
			AckCircleSearch,
			AckCircleChatList,
			NotiCircleChatNotimessage,
		};
	}
}
namespace ProductC2S
{
	public class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID ReqAddItemSlot = (Nettention.Proud.RmiID)31000+1;
			public const Nettention.Proud.RmiID ReqApplyPosCard = (Nettention.Proud.RmiID)31000+2;
			public const Nettention.Proud.RmiID ReqApplyOutPosCard = (Nettention.Proud.RmiID)31000+3;
			public const Nettention.Proud.RmiID ReqSellCard = (Nettention.Proud.RmiID)31000+4;
			public const Nettention.Proud.RmiID ReqSetLockCard = (Nettention.Proud.RmiID)31000+5;
			public const Nettention.Proud.RmiID ReqChangeTypeCard = (Nettention.Proud.RmiID)31000+6;
			public const Nettention.Proud.RmiID ReqLvUpCard = (Nettention.Proud.RmiID)31000+7;
			public const Nettention.Proud.RmiID ReqSkillLvUpCard = (Nettention.Proud.RmiID)31000+8;
			public const Nettention.Proud.RmiID ReqWakeCard = (Nettention.Proud.RmiID)31000+9;
			public const Nettention.Proud.RmiID ReqEnchantCard = (Nettention.Proud.RmiID)31000+10;
			public const Nettention.Proud.RmiID ReqFavorLvRewardCard = (Nettention.Proud.RmiID)31000+11;
			public const Nettention.Proud.RmiID ReqDecomposition = (Nettention.Proud.RmiID)31000+12;
			public const Nettention.Proud.RmiID ReqSellItem = (Nettention.Proud.RmiID)31000+13;
			public const Nettention.Proud.RmiID ReqItemExchangeCash = (Nettention.Proud.RmiID)31000+14;
			public const Nettention.Proud.RmiID ReqUseItem = (Nettention.Proud.RmiID)31000+15;
			public const Nettention.Proud.RmiID ReqUseItemGoods = (Nettention.Proud.RmiID)31000+16;
			public const Nettention.Proud.RmiID ReqSellGem = (Nettention.Proud.RmiID)31000+17;
			public const Nettention.Proud.RmiID ReqSetLockGem = (Nettention.Proud.RmiID)31000+18;
			public const Nettention.Proud.RmiID ReqResetOptGem = (Nettention.Proud.RmiID)31000+19;
			public const Nettention.Proud.RmiID ReqResetOptSelectGem = (Nettention.Proud.RmiID)31000+20;
			public const Nettention.Proud.RmiID ReqLvUpGem = (Nettention.Proud.RmiID)31000+21;
			public const Nettention.Proud.RmiID ReqWakeGem = (Nettention.Proud.RmiID)31000+22;
			public const Nettention.Proud.RmiID ReqEvolutionGem = (Nettention.Proud.RmiID)31000+23;
			public const Nettention.Proud.RmiID ReqAnalyzeGem = (Nettention.Proud.RmiID)31000+24;
			public const Nettention.Proud.RmiID ReqSellWeapon = (Nettention.Proud.RmiID)31000+25;
			public const Nettention.Proud.RmiID ReqSetLockWeapon = (Nettention.Proud.RmiID)31000+26;
			public const Nettention.Proud.RmiID ReqLvUpWeapon = (Nettention.Proud.RmiID)31000+27;
			public const Nettention.Proud.RmiID ReqWakeWeapon = (Nettention.Proud.RmiID)31000+28;
			public const Nettention.Proud.RmiID ReqEnchantWeapon = (Nettention.Proud.RmiID)31000+29;
			public const Nettention.Proud.RmiID ReqSkillLvUpWeapon = (Nettention.Proud.RmiID)31000+30;
			public const Nettention.Proud.RmiID ReqApplyGemInWeapon = (Nettention.Proud.RmiID)31000+31;
			public const Nettention.Proud.RmiID ReqAddSlotInWpnDepot = (Nettention.Proud.RmiID)31000+32;
			public const Nettention.Proud.RmiID ReqApplySlotInWpnDepot = (Nettention.Proud.RmiID)31000+33;
			public const Nettention.Proud.RmiID ReqApplyPosBadge = (Nettention.Proud.RmiID)31000+34;
			public const Nettention.Proud.RmiID ReqApplyOutPosBadge = (Nettention.Proud.RmiID)31000+35;
			public const Nettention.Proud.RmiID ReqSellBadge = (Nettention.Proud.RmiID)31000+36;
			public const Nettention.Proud.RmiID ReqSetLockBadge = (Nettention.Proud.RmiID)31000+37;
			public const Nettention.Proud.RmiID ReqUpgradeBadge = (Nettention.Proud.RmiID)31000+38;
			public const Nettention.Proud.RmiID ReqResetUpgradeBadge = (Nettention.Proud.RmiID)31000+39;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			ReqAddItemSlot,
			ReqApplyPosCard,
			ReqApplyOutPosCard,
			ReqSellCard,
			ReqSetLockCard,
			ReqChangeTypeCard,
			ReqLvUpCard,
			ReqSkillLvUpCard,
			ReqWakeCard,
			ReqEnchantCard,
			ReqFavorLvRewardCard,
			ReqDecomposition,
			ReqSellItem,
			ReqItemExchangeCash,
			ReqUseItem,
			ReqUseItemGoods,
			ReqSellGem,
			ReqSetLockGem,
			ReqResetOptGem,
			ReqResetOptSelectGem,
			ReqLvUpGem,
			ReqWakeGem,
			ReqEvolutionGem,
			ReqAnalyzeGem,
			ReqSellWeapon,
			ReqSetLockWeapon,
			ReqLvUpWeapon,
			ReqWakeWeapon,
			ReqEnchantWeapon,
			ReqSkillLvUpWeapon,
			ReqApplyGemInWeapon,
			ReqAddSlotInWpnDepot,
			ReqApplySlotInWpnDepot,
			ReqApplyPosBadge,
			ReqApplyOutPosBadge,
			ReqSellBadge,
			ReqSetLockBadge,
			ReqUpgradeBadge,
			ReqResetUpgradeBadge,
		};
	}
}
namespace ProductS2C
{
	public class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID AckAddItemSlot = (Nettention.Proud.RmiID)31050+1;
			public const Nettention.Proud.RmiID AckApplyPosCard = (Nettention.Proud.RmiID)31050+2;
			public const Nettention.Proud.RmiID AckApplyOutPosCard = (Nettention.Proud.RmiID)31050+3;
			public const Nettention.Proud.RmiID AckSellCard = (Nettention.Proud.RmiID)31050+4;
			public const Nettention.Proud.RmiID AckSetLockCard = (Nettention.Proud.RmiID)31050+5;
			public const Nettention.Proud.RmiID AckChangeTypeCard = (Nettention.Proud.RmiID)31050+6;
			public const Nettention.Proud.RmiID AckLvUpCard = (Nettention.Proud.RmiID)31050+7;
			public const Nettention.Proud.RmiID AckSkillLvUpCard = (Nettention.Proud.RmiID)31050+8;
			public const Nettention.Proud.RmiID AckWakeCard = (Nettention.Proud.RmiID)31050+9;
			public const Nettention.Proud.RmiID AckEnchantCard = (Nettention.Proud.RmiID)31050+10;
			public const Nettention.Proud.RmiID AckFavorLvRewardCard = (Nettention.Proud.RmiID)31050+11;
			public const Nettention.Proud.RmiID AckDecomposition = (Nettention.Proud.RmiID)31050+12;
			public const Nettention.Proud.RmiID AckSellItem = (Nettention.Proud.RmiID)31050+13;
			public const Nettention.Proud.RmiID AckItemExchangeCash = (Nettention.Proud.RmiID)31050+14;
			public const Nettention.Proud.RmiID AckUseItemGoods = (Nettention.Proud.RmiID)31050+15;
			public const Nettention.Proud.RmiID AckUseItemProduct = (Nettention.Proud.RmiID)31050+16;
			public const Nettention.Proud.RmiID AckUseItemCode = (Nettention.Proud.RmiID)31050+17;
			public const Nettention.Proud.RmiID AckUseItemStageSpecial = (Nettention.Proud.RmiID)31050+18;
			public const Nettention.Proud.RmiID AckSellGem = (Nettention.Proud.RmiID)31050+19;
			public const Nettention.Proud.RmiID AckSetLockGem = (Nettention.Proud.RmiID)31050+20;
			public const Nettention.Proud.RmiID AckResetOptGem = (Nettention.Proud.RmiID)31050+21;
			public const Nettention.Proud.RmiID AckResetOptSelectGem = (Nettention.Proud.RmiID)31050+22;
			public const Nettention.Proud.RmiID AckLvUpGem = (Nettention.Proud.RmiID)31050+23;
			public const Nettention.Proud.RmiID AckWakeGem = (Nettention.Proud.RmiID)31050+24;
			public const Nettention.Proud.RmiID AckEvolutionGem = (Nettention.Proud.RmiID)31050+25;
			public const Nettention.Proud.RmiID AckAnalyzeGem = (Nettention.Proud.RmiID)31050+26;
			public const Nettention.Proud.RmiID AckSellWeapon = (Nettention.Proud.RmiID)31050+27;
			public const Nettention.Proud.RmiID AckSetLockWeapon = (Nettention.Proud.RmiID)31050+28;
			public const Nettention.Proud.RmiID AckLvUpWeapon = (Nettention.Proud.RmiID)31050+29;
			public const Nettention.Proud.RmiID AckSkillLvUpWeapon = (Nettention.Proud.RmiID)31050+30;
			public const Nettention.Proud.RmiID AckWakeWeapon = (Nettention.Proud.RmiID)31050+31;
			public const Nettention.Proud.RmiID AckEnchantWeapon = (Nettention.Proud.RmiID)31050+32;
			public const Nettention.Proud.RmiID AckApplyGemInWeapon = (Nettention.Proud.RmiID)31050+33;
			public const Nettention.Proud.RmiID AckAddSlotInWpnDepot = (Nettention.Proud.RmiID)31050+34;
			public const Nettention.Proud.RmiID AckApplySlotInWpnDepot = (Nettention.Proud.RmiID)31050+35;
			public const Nettention.Proud.RmiID AckApplyPosBadge = (Nettention.Proud.RmiID)31050+36;
			public const Nettention.Proud.RmiID AckApplyOutPosBadge = (Nettention.Proud.RmiID)31050+37;
			public const Nettention.Proud.RmiID AckSellBadge = (Nettention.Proud.RmiID)31050+38;
			public const Nettention.Proud.RmiID AckSetLockBadge = (Nettention.Proud.RmiID)31050+39;
			public const Nettention.Proud.RmiID AckUpgradeBadge = (Nettention.Proud.RmiID)31050+40;
			public const Nettention.Proud.RmiID AckResetUpgradeBadge = (Nettention.Proud.RmiID)31050+41;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			AckAddItemSlot,
			AckApplyPosCard,
			AckApplyOutPosCard,
			AckSellCard,
			AckSetLockCard,
			AckChangeTypeCard,
			AckLvUpCard,
			AckSkillLvUpCard,
			AckWakeCard,
			AckEnchantCard,
			AckFavorLvRewardCard,
			AckDecomposition,
			AckSellItem,
			AckItemExchangeCash,
			AckUseItemGoods,
			AckUseItemProduct,
			AckUseItemCode,
			AckUseItemStageSpecial,
			AckSellGem,
			AckSetLockGem,
			AckResetOptGem,
			AckResetOptSelectGem,
			AckLvUpGem,
			AckWakeGem,
			AckEvolutionGem,
			AckAnalyzeGem,
			AckSellWeapon,
			AckSetLockWeapon,
			AckLvUpWeapon,
			AckSkillLvUpWeapon,
			AckWakeWeapon,
			AckEnchantWeapon,
			AckApplyGemInWeapon,
			AckAddSlotInWpnDepot,
			AckApplySlotInWpnDepot,
			AckApplyPosBadge,
			AckApplyOutPosBadge,
			AckSellBadge,
			AckSetLockBadge,
			AckUpgradeBadge,
			AckResetUpgradeBadge,
		};
	}
}

				 
