
using System.Collections;
using System.Collections.Generic;
using System.Runtime.InteropServices;


/*[StructLayout(LayoutKind.Explicit)]
public struct sUnion
{
    [FieldOffset(0)] int asInteger;
    [FieldOffset(0)] float asFloat;
    [FieldOffset(0)] bool asBool;
    [FieldOffset(0)] int asStringId;
}

public struct sVariant
{
    enum eType
    {
        Integer,
        Float,
        Bool,
        StringId,

        Count,
    }

    eType type;
    sUnion value;
}*/


public enum eEventType
{
    EVENT_NONE = 0,

    //=================================
    // Play
    //=================================

    // Player
    EVENT_PLAYER_INPUT_DIR = 1,
    EVENT_PLAYER_INPUT_DIR_AUTO,
    EVENT_PLAYER_INPUT_JUMP,
    EVENT_PLAYER_INPUT_DEFENCE,
    EVENT_PLAYER_INPUT_ATK,
    EVENT_PLAYER_INPUT_CHARGE_ATK_START,
    EVENT_PLAYER_INPUT_CHARGE_ATK_END,
    EVENT_PLAYER_INPUT_SPECIAL_ATK, // 일반공격 중에 나가는 특수공격
    EVENT_PLAYER_INPUT_ATK_PRESS_START,
    EVENT_PLAYER_INPUT_ATK_PRESS_END,
    EVENT_PLAYER_INPUT_ATK_TOUCH_END,
    EVENT_PLAYER_INPUT_ULTIMATE_SKILL,
    EVENT_PLAYER_INPUT_WEAPON_SKILL,
    _END_EVENT_PLAYER_INPUT = 99,

    // Game
    EVENT_GAME_PLAYER_DEAD = 100,
    EVENT_GAME_ENEMY_DEAD,
    EVENT_GAME_ALL_ENEMY_DEAD,
    EVENT_GAME_ENEMY_BOSS_APPEAR,
    EVENT_GAME_ENEMY_BOSS_DIE,
    //EVENT_GAME_ENEMY_BOSS_DIE_AFTER_DIRECTOR,
    EVENT_GAME_OTHER_OBJECT_DEAD,
    EVENT_GAME_PASS_PORTAL,
    EVENT_GAME_END_TIMER,
    EVENT_GAME_STAGE_CONTINUE,
    EVENT_GAME_REMOVE_HIT_TARGET,
    _END_EVENT_GAME = 199,

    // Battle
    EVENT_BATTLE_ON_MELEE_ATTACK = 200,
    EVENT_BATTLE_ON_PROJECTILE_ATTACK,
    EVENT_BATTLE_ON_DIRECT_HIT,
    EVENT_BATTLE_DAMAGE_ONCE,
    EVENT_BATTLE_STACK_ON_HIT_DAMAGE_ONCE,  // 피격 시 스택이 쌓이고 맥스치까지 쌓였을 때 적에게 한방 공격
    EVENT_BATTLE_STACK_ON_COMBO_POWER_UP,   // 콤보 시 스택이 쌓이고 맥스치까지 쌓였을 때 공격력 증가
    EVENT_BATTLE_ON_HITTER_DIE,             // 맞은 놈이 죽었을 때
    EVENT_BATTLE_SUMMON_PLAYER_MINION,      // PlayerMinion이 소환됐을 때
    _END_EVENT_BATTLE = 299,

    // Action/Projectile/Etc..
    EVENT_ACTION_COMMAND_FROM_BATTLE_OPTION = 300,
    EVENT_ACTION_FIRE_PROJECTILE,
	EVENT_ACTION_FIRE_PROJECTILE_REGARDLESS_TARGET_COUNT,
	EVENT_ACTION_FIRE_PROJECTILE_REPEAT,
	EVENT_ACTION_SET_SPRINT_START_TIME_RATE,
    EVENT_ACTION_SET_ONLY_LAST_MELEE_ATTACK,
    EVENT_ACTION_SET_LAST_MELEE_ATTACK_KNOCKBACK,
    EVENT_ACTION_HIT_ATTACK,
    EVENT_ACTION_HIT_UPPER_ATTACK,
    EVENT_ACTION_HIT_KNOCKBACK_ATTACK,
    EVENT_ACTION_HIT_DOWN_ATTACK,
    EVENT_ACTION_HIT_STUN_ATTACK,
    EVENT_ACTION_HIT_GROGGY_ATTACK,
	EVENT_ACTION_HIT_ATTACK_CRITICAL,
    EVENT_ACTION_HIT_ATTACK_REPEAT,
    EVENT_ACTION_REFLECTION,
    EVENT_ACTION_REFLECTION_AROUND,
    EVENT_ATTACK_ADD,
    EVENT_SP_ATTACK_ADD,
    EVENT_ATTACK_USING_ACCUM_DAMAGE,
    EVENT_ITEM_DROP,
    EVENT_COMBO_RESET_BY_HIT,
    EVENT_SUPPORTER_COOL_TIME_DECREASE,
    EVENT_SUPPORTER_COOL_TIME_DECREASE_IN_REAL_TIME,
    EVENT_SKILL_COOL_TIME_DECREASE,
    EVENT_SKILL_ACTION_COOL_TIME_DECREASE,
    EVENT_SKILL_ACTION_COOL_TIME_DECREASE_IN_REAL_TIME,
    EVENT_SKILL_ONE_ACTION_COOL_TIME_DECREASE_SEC,
    EVENT_SKILL_ONLY_ACTION_COOL_TIME_DECREASE_SEC,
    EVENT_SP_REGEN_INC_RATE,
    EVENT_SET_ADD_ACTION,
    EVENT_SET_ADD_ACTION_AUTO_RELEASE,
    EVENT_INCREASE_ADD_ACTION_VALUE,
    EVENT_SUMMONS_ATTACK_POWER_INCREASE,
    EVENT_BLACKHOLE,
    EVENT_HIDE,
	EVENT_SUMMON_PLAYER_MINION,
    EVENT_SUMMON_PLAYER_MINION_BY_DIE_ENEMY_COUNT,
    EVENT_SUMMON_OFF_PLAYER_MINION,
	EVENT_SKILL_RESET_ACTION_COOL_TIME_BY_USE_SP,
    EVENT_SKILL_RESET_ALL_COOL_TIME,
    EVENT_RANDOM_SKILL_RESET,
    EVENT_PUSHED,
    EVENT_DEATH,
    EVENT_INCREASE_CHAR_SKILL_COOL_TIME,
    EVENT_INCREASE_CHAR_SUPPORTER_SKILL_COOL_TIME,
    EVENT_SET_EXTRA_PLAYER_FUNC,

    _END_EVENT_ACTION = 399,

    // QTE
    EVENT_QTE_SUCCESS_EVADE = 400,
    EVENT_QTE_HIT_DOWN_ATTACK,
    EVENT_QTE_HIT_KNOCKBACK_ATTACK,
    EVENT_QTE_HIT_UPPER_ATTACK,
    EVENT_QTE_END,
    _END_EVENT_QTE = 499,
    
    // 대마살법
    EVENT_SKILL_CLONE_ATTACK = 500,
    EVENT_SKILL_DOWN_ATTACK,
    _END_EVENT_SKILL = 599,

    // Enemy
    EVENT_ENEMY_SNAKELADY_CHANGE_ACTION = 600,
    _END_EVENT_ENEMY = 699,

    // Buff/Debuff Stats
    EVENT_STAT_CRITICAL_RATE_UP = 700,
    EVENT_STAT_CRITICAL_RATE_DOWN,
	EVENT_STAT_CRITICAL_RATE_UP_WITH_ACTIVE_ENEMY_COUNT_RATIO,
	EVENT_STAT_CRITICAL_RATE_DOWN_WITH_ACTIVE_ENEMY_COUNT_RATIO,
	EVENT_STAT_CRITICAL_DMG_UP,
    EVENT_STAT_CRITICAL_DMG_DOWN,
    EVENT_STAT_CRITICAL_RESIST_UP,
    EVENT_STAT_CRITICAL_RESIST_DOWN,
    EVENT_STAT_CRITICAL_DEF_UP,
    EVENT_STAT_CRITICAL_DEF_DOWN,
    EVENT_STAT_SPEED_UP,
    EVENT_STAT_SPEED_DOWN,
    EVENT_STAT_ATKPOWER_TO_SHIELD_RATE_UP,
    EVENT_STAT_ATKPOWER_TO_SHIELD_RATE_DOWN,
    EVENT_STAT_ULTIMATESKILL_ATKPOWER_RATE_UP,
    EVENT_STAT_ULTIMATESKILL_ATKPOWER_RATE_DOWN,
    EVENT_STAT_DMG_RATE_DOWN,
	EVENT_STAT_DMG_RATE_UP_WITH_ACTIVE_ENEMY_COUNT_RATIO,
	EVENT_STAT_DMG_RATE_DOWN_WITH_ACTIVE_ENEMY_COUNT_RATIO,
	EVENT_STAT_DMG_RATE_DOWN_BY_BUFF_COUNT,
	EVENT_STAT_DMG_RATE_UP,
    EVENT_STAT_ATKPOWER_RATE_UP,
    EVENT_STAT_ATKPOWER_RATE_UP_ONCE,
	EVENT_STAT_ATKPOWER_RATE_UP_BY_BUFF_COUNT,
    EVENT_STAT_ATKPOWER_RATE_UP_BY_ENEMY_DEBUFF_STACK,
    EVENT_STAT_ATKPOWER_RATE_UP_WITH_ACTIVE_ENEMY_COUNT_RATIO,
    EVENT_STAT_ATKPOWER_RATE_DOWN,
    EVENT_STAT_ATKPOWER_RATE_DOWN_WITH_ACTIVE_ENEMY_COUNT_RATIO,
	EVENT_STAT_HEAL_RATE_UP,
    EVENT_STAT_HEAL_RATE_DOWN,
    EVENT_STAT_DEMONS_AURA,
    EVENT_STAT_TIME_DEBUFF_REDUCE,
    EVENT_STAT_TIME_DEBUFF_PROMOTE,
    EVENT_STAT_SP_ADD_INC_RATE,
    EVENT_STAT_SP_ADD_DEC_RATE,
    EVENT_STAT_ADD_BUFF_DEBUFF_DURATION,
    EVENT_STAT_PENETRATE_UP,
    EVENT_STAT_SUFFERANCE_UP,
    _END_EVENT_STAT = 799,

    // Buff/Debuff
    EVENT_BUFF_SPEED_UP = 800,
    EVENT_BUFF_SPEED_UP_ON_EFFECT,
    EVENT_BUFF_BLOODSUCKING,
    EVENT_BUFF_DOT_HEAL,
    EVENT_BUFF_HEAL,
    EVENT_BUFF_HEAL_ON_DIE_IN_TIME,
    EVENT_BUFF_DOT_HEAL_ABS,
    EVENT_BUFF_HEAL_ABS,
    EVENT_BUFF_DOT_HEAL_COST_HP,
    EVENT_BUFF_HEAL_COST_HP,
    EVENT_BUFF_DOT_HEAL_COST_HP_CONDI,
    EVENT_BUFF_ADD_SP,
    EVENT_BUFF_DMG_RATE_DOWN,
    EVENT_BUFF_DMG_RATE_DOWN_WITH_ACCUM_DAMAGE,
    EVENT_BUFF_ATKPOWER_RATE_UP,
    EVENT_BUFF_ATKPOWER_TO_SHIELD_RATE_UP,
    EVENT_BUFF_ULTIMATESKILL_ATKPOWER_RATE_UP,
    EVENT_BUFF_HEAL_RATE_UP,
    EVENT_BUFF_CRITICAL_RATE_UP,
    EVENT_BUFF_CRITICAL_DMG_UP,
    EVENT_BUFF_CRITICAL_RESIST_UP,
    EVENT_BUFF_CRITICAL_DEF_UP,
    EVENT_BUFF_REFLECTION,
    EVENT_BUFF_REFLECTION_AROUND,
    EVENT_BUFF_RANDOM_KNOCKBACK,
    EVENT_BUFF_SUPER_ARMOR,
    EVENT_BUFF_CONDITIONAL_SUPER_ARMOR,
    EVENT_BUFF_INCREASE_SUPER_ARMOR_BY_SKILL,
    EVENT_BUFF_IGNORE_CRI_RATE,
    EVENT_BUFF_CLEAR_DEBUFF,
    EVENT_BUFF_REMOVE_DEBUFF,
    EVENT_BUFF_REMOVE_DEBUFF_AND_INCAPABLE,
    EVENT_BUFF_HOLD_POSITION,
    EVENT_BUFF_DOT_DMG_TO_TARGET,
    EVENT_BUFF_ATTACK_TO_TARGET,
    EVENT_BUFF_TIME_DEBUFF_REDUCE,
    EVENT_BUFF_SP_ADD_INC_RATE,
    EVENT_BUFF_ADD_MAX_HP,
    EVENT_BUFF_ADD_BUFF_DEBUFF_DURATION,
    EVENT_BUFF_SET_DEBUFF_IMMUNE,
    EVENT_BUFF_PENETRATE_UP,
    EVENT_BUFF_SUFFERANCE_UP,
    EVENT_DEBUFF_SPEED_DOWN,
    EVENT_DEBUFF_SPEED_DOWN_AND_SKIP_CUR_ANI,
    EVENT_DEBUFF_SPEED_DOWN_TO_TARGET,
    EVENT_DEBUFF_DOT_DMG,
    EVENT_DEBUFF_DMG_RATE_UP,
    EVENT_DEBUFF_ATKPOWER_RATE_DOWN,
    EVENT_DEBUFF_ATKPOWER_TO_SHIELD_RATE_DOWN,
    EVENT_DEBUFF_ULTIMATESKILL_ATKPOWER_RATE_DOWN,
    EVENT_DEBUFF_HEAL_RATE_DOWN,
    EVENT_DEBUFF_CRITICAL_RATE_DOWN,
    EVENT_DEBUFF_CRITICAL_DMG_DOWN,
    EVENT_DEBUFF_CRITICAL_RESIST_DOWN,
    EVENT_DEBUFF_CRITICAL_DEF_DOWN,
    EVENT_DEBUFF_DOT_SHIELD_DMG,
    EVENT_DEBUFF_BREAK_SHIELD,
    EVENT_DEBUFF_SKIP_ATTACK,
    EVENT_DEBUFF_HOLD_POSITION,
    EVENT_DEBUFF_TIME_DEBUFF_PROMOTE,
    EVENT_DEBUFF_CLEAR_BUFF,
    EVENT_DEBUFF_REMOVE_BUFF,
    EVENT_DEBUFF_DECREASE_SP,
    EVENT_DEBUFF_SP_ADD_DEC_RATE,
    EVENT_DEBUFF_MOVEMENT_INVERSE,
    EVENT_DEBUFF_FREEZE,
    EVENT_BUFF_COMMAND_CLONE_ATTACK02,
    EVENT_DEBUFF_MARKING,
    EVENT_DEBUFF_HOLD_SUPPORTER_SKILL_COOLTIME,
	EVENT_DEBUFF_ELECTRIC_SHOCK,
	EVENT_BUFF_LIGHTNING_ATTACK,
    EVENT_BUFF_FIRE_AURA,
    EVENT_DEBUFF_USE_SP,

    // Immune
    EVENT_IMMUNE_ATKATTR = 900,
    EVENT_IMMUNE_ATKPOWER_RATE_DOWN,
    EVENT_IMMUNE_DMG_RATE_UP,
    EVENT_IMMUNE_SPEED_DOWN,

    _END_EVENT_BUFF = 999,

    //=================================
    // Lobby
    //=================================

    EVENT_LOBBY_START_FIGURE_EDIT = 1100,
    EVENT_LOBBY_END_FIGURE_EDIT,
    _END_EVENT_LOBBY = 1199,

    //=================================
    // Lobby
    //=================================
    EVENT_RACE_FAILED = 1200,
    EVENT_RACE_SUCCESS,
    _END_EVENT_RACE = 1299,
}

[System.Flags]
public enum eEventSubject
{
    None = 0,

    Self                    = 1 << 1,
    Player                  = 1 << 2,
    MainTarget              = 1 << 3,
    HitTargetList           = 1 << 4,
    HitTargetDie            = 1 << 5,
    OnHitTargetDie          = 1 << 6,
    ActiveEnemies           = 1 << 7,
    ActiveEnemiesInRange    = 1 << 8,
    Caster                  = 1 << 9,
    Attacker                = 1 << 10,
    Action                  = 1 << 11,
    FireProjectile          = 1 << 12,
    World                   = 1 << 13,
    Lobby                   = 1 << 14,
    OnHitActionEnemies      = 1 << 15,
    PlayerSummons           = 1 << 16,
    SelectTarget            = 1 << 17,
	AppearEnemy				= 1 << 18,
    PlayerAll               = 1 << 19,
    HitTargetListOnce       = 1 << 20,
    PlayerAllInRange        = 1 << 21,

    All = int.MaxValue
}


public class BaseEvent
{
    public eEventType       eventType       { get; set; }
    public eEventSubject    eventSubject    { get; set; }
    public Unit             sender          { get; set; }
    public Unit             CompareUnit     { get; set; } = null;
    public Unit             SelectTarget    { get; set; } = null;
	public bool				Ignore			{ get; set; } = false;

    public float value  { get; set; }
    public float value2 { get; set; }
    public float value3 { get; set; }

    public BattleOption.sBattleOptionData battleOptionData { get; protected set; } = new BattleOption.sBattleOptionData();


    public void SetBattleOptionData(BattleOption.sBattleOptionData data)
    {
        battleOptionData = data;
    }
}
